version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: daily
      time: "15:30"
    assignees:
      - "octocat"
    labels:
      - "composer"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: daily
      time: "15:30"
    assignees:
      - "octocat"
    labels:
      - "yarn"
      - "dependencies"
